"""add sitter_note to care_assignments and allow pending status

Revision ID: 28b4f2557d9f
Revises: 7f93a73b1830
Create Date: 2025-08-24 13:57:58.291972

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '28b4f2557d9f'
down_revision = '7f93a73b1830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('care_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_care_offers_care_request_id'))
        batch_op.drop_index(batch_op.f('ix_care_offers_sitter_id'))

    op.drop_table('care_offers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_offers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('care_request_id', sa.INTEGER(), nullable=False),
    sa.Column('sitter_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['care_request_id'], ['care_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sitter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('care_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_care_offers_sitter_id'), ['sitter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_care_offers_care_request_id'), ['care_request_id'], unique=False)

    # ### end Alembic commands ###
