"""create care_requests table

Revision ID: 7019c078b9e8
Revises: b399fb1d4474
Create Date: 2025-08-23 20:41:36.159066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7019c078b9e8'
down_revision = 'b399fb1d4474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('location_text', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_at > start_at', name='ck_care_end_after_start'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('care_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_care_requests_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_care_requests_pet_id'), ['pet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('care_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_care_requests_pet_id'))
        batch_op.drop_index(batch_op.f('ix_care_requests_owner_id'))

    op.drop_table('care_requests')
    # ### end Alembic commands ###
